package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import main.Main;
import javafx.beans.property.SimpleStringProperty;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ChoiceBox;

import java.net.URL;
import java.util.Optional;
import java.util.ResourceBundle;

import controller.LieferantController;

public class LieferantBearbeitenController implements Initializable {
	@FXML
	private Label lblHeader;
	@FXML
	private Label lblName;
	@FXML
	private Label lblAddr;
	@FXML
	private Label lblStadt;
	@FXML
	private Label lblPLZ;
	@FXML
	private Label lblLand;
	@FXML
	private Label lblTyp;
	@FXML
	private TextField textfieldName;
	@FXML
	private TextField textfieldAddr;
	@FXML
	private TextField textfieldStadt;
	@FXML
	private TextField textFieldPLZ;
	@FXML
	private ChoiceBox<?> choiceboxLand;
	@FXML
	private ChoiceBox<?> choiceboxLTyp;
	@FXML
	private Label lblMail;
	@FXML
	private Label lblTelefon;
	@FXML
	private Label lblBank;
	@FXML
	private Label lblIBAN;
	@FXML
	private Label lblSWIFT;
	@FXML
	private Label lblSteuer;
	@FXML
	private TextField textfieldMail;
	@FXML
	private TextField textfieldTelnum;
	@FXML
	private TextField textfieldBank;
	@FXML
	private TextField textfieldIBAN;
	@FXML
	private TextField textfieldSWIFT;
	@FXML
	private TextField textfieldSteuer;
	@FXML
	private Button btnSpeichern;
	@FXML
	private Button btnAbbrechen;
	private controller.LieferantController lc;
	public SimpleStringProperty nameDisplay = new SimpleStringProperty("");

	// Event Listener on Button[#btnSpeichern].onAction
	@FXML
	public void handleSpeichernAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAbbrechen].onAction
	@FXML
	public void handleAbbrechenAction(ActionEvent event) {
		//When "Abbrechen"-Button is 
		//pressed the application routes the user back to the home screen (pane with idx=1)
		Alert alert = new Alert(AlertType.CONFIRMATION);
		alert.setTitle("Bearbeitung abbrechen");
		alert.setHeaderText("Der Prozess wird abgebrochen.");
		alert.setContentText("Wollen Sie wirklich den Prozess abbrechen?");
		Optional<ButtonType> result = alert.showAndWait();
		if (result.get() == ButtonType.OK){
			alert.close();
			Main.set_pane(2);
			textfieldName.clear();
			textfieldAddr.clear();
			textfieldStadt.clear();
			textFieldPLZ.clear();
			textFieldPLZ.clear();
			textfieldMail.clear();
			textfieldTelnum.clear();
			textfieldBank.clear();
			textfieldIBAN.clear();
			textfieldSWIFT.clear();
			textfieldSteuer.clear();
		}
		else {
			alert.close();
		}
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		textfieldName.setText(nameDisplay.getValue());
	
	}
}
